In [1]:
kanto = [73, 67, 43]
johto = [91, 88, 64]
hoenn = [87, 134, 58]
sinnoh = [102, 43, 37]
unova = [69, 96, 70]

w1, w2, w3 = 0.3, 0.2, 0.5
weights = [w1, w2, w3]

In [2]:
weights

[0.3, 0.2, 0.5]

In [6]:
def crop_yield(region, weights):
    result = 0
    for x, w in zip(region, weights):
        result += x * w
    return result

In [8]:
print(crop_yield(kanto, weights))
print(crop_yield(johto, weights))
print(crop_yield(unova, weights))

56.8
76.9
74.9


In [10]:
weights[0]

0.3

In [11]:
import numpy as np

In [14]:
kanto = np.array([73, 67, 43])
kanto

array([73, 67, 43])

In [16]:
weights = np.array([w1, w2, w3])
weights

array([0.3, 0.2, 0.5])

In [17]:
## Dot product
print(np.dot(kanto, weights))
## element-wise multiplication and sum
(kanto * weights).sum()

56.8


56.8

In [18]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr1 * arr2

array([ 4, 10, 18])

In [19]:
print(arr2.sum())

15


In [20]:
# Python lists
arr1 = list(range(1000000))
arr2 = list(range(1000000, 2000000))

# Numpy arrays
arr1_np = np.array(arr1)
arr2_np = np.array(arr2)

In [22]:
%%time
result = 0
for x1, x2 in zip(arr1, arr2):
    result += x1*x2
print(result)

833332333333500000
CPU times: user 219 ms, sys: 0 ns, total: 219 ms
Wall time: 219 ms


In [23]:
%%time
np.dot(arr1_np, arr2_np)

CPU times: user 3.11 ms, sys: 0 ns, total: 3.11 ms
Wall time: 2.14 ms


833332333333500000

In [24]:
climate_data = np.array([[73, 67, 43],
                         [91, 88, 64],
                         [87, 134, 58],
                         [102, 43, 37],
                         [69, 96, 70]])
climate_data

array([[ 73,  67,  43],
       [ 91,  88,  64],
       [ 87, 134,  58],
       [102,  43,  37],
       [ 69,  96,  70]])

In [28]:
np.dot(climate_data[0],climate_data[1])

15291

In [29]:
# 2D array (matrix)
climate_data.shape

(5, 3)

In [30]:
weights

array([0.3, 0.2, 0.5])

In [31]:
weights.shape

(3,)

In [32]:
# 3D array 
arr3 = np.array([
    [[11, 12, 13], 
     [13, 14, 15]], 
    [[15, 16, 17], 
     [17, 18, 19.5]]])

In [33]:
np.matmul(climate_data, weights)

array([56.8, 76.9, 81.9, 57.7, 74.9])

## Working with CSV data files

In [34]:
import urllib.request

urllib.request.urlretrieve(
    'https://hub.jovian.ml/wp-content/uploads/2020/08/climate.csv', 
    'climate.txt')

('climate.txt', <http.client.HTTPMessage at 0x7fb675159950>)

In [35]:
## To read this file into a numpy array, we can use the genfromtxt function.
climate_data = np.genfromtxt('climate.txt', delimiter=',', skip_header=1)

In [36]:
climate_data

array([[25., 76., 99.],
       [39., 65., 70.],
       [59., 45., 77.],
       ...,
       [99., 62., 58.],
       [70., 71., 91.],
       [92., 39., 76.]])

In [37]:
climate_data.shape

(10000, 3)

In [38]:
weights = np.array([0.3, 0.2, 0.5])

In [40]:
yields = np.matmul(climate_data, weights)
yields.shape

(10000,)

In [45]:
(yields)

array([72.2, 59.7, 65.2, ..., 71.1, 80.7, 73.4])

In [46]:
climate_data_results = np.concatenate((climate_data, yields.reshape(len(yields), 1)), axis=1)

In [47]:
climate_data_results

array([[25. , 76. , 99. , 72.2],
       [39. , 65. , 70. , 59.7],
       [59. , 45. , 77. , 65.2],
       ...,
       [99. , 62. , 58. , 71.1],
       [70. , 71. , 91. , 80.7],
       [92. , 39. , 76. , 73.4]])

In [48]:
climate_data_results.shape

(10000, 4)

There are a couple of subtleties here:

* Since we wish to add new columns, we pass the argument `axis=1` to `np.concatenate`. The `axis` argument specifies the dimension for concatenation.

*  The arrays should have the same number of dimensions, and the same length along each except the dimension used for concatenation. We use the [`np.reshape`](https://numpy.org/doc/stable/reference/generated/numpy.reshape.html) function to change the shape of `yields` from `(10000,)` to `(10000,1)`.

Here's a visual explanation of `np.concatenate` along `axis=1` (can you guess what `axis=0` results in?):

<img src="https://www.w3resource.com/w3r_images/python-numpy-image-exercise-58.png" width="300">

The best way to understand what a Numpy function does is to experiment with it and read the documentation to learn about its arguments & return values. Use the cells below to experiment with `np.concatenate` and `np.reshape`.

In [49]:
np.savetxt('climate_results.txt', 
           climate_data_results, 
           fmt='%.2f', 
           delimiter=',',
           header='temperature,rainfall,humidity,yeild_apples', 
           comments='')

In [50]:
climate_data_results

array([[25. , 76. , 99. , 72.2],
       [39. , 65. , 70. , 59.7],
       [59. , 45. , 77. , 65.2],
       ...,
       [99. , 62. , 58. , 71.1],
       [70. , 71. , 91. , 80.7],
       [92. , 39. , 76. , 73.4]])

In [51]:
arr2 = np.array([[1,2,3,4],
                 [5,6,7,8],
                 [9,1,2,3]                 
                  ])
arr2.shape

(3, 4)

In [52]:
arr4 = np.array([4, 5, 6, 7])
arr4.shape

(4,)

In [53]:
arr2 + arr4

array([[ 5,  7,  9, 11],
       [ 9, 11, 13, 15],
       [13,  6,  8, 10]])